source 'https://rubygems.org'
ruby '2.2.6'

gem 'rack'
gem 'octokit', '~> 4.6'
gem 'libxslt-ruby', '> 0'
gem 'libxml-ruby', '> 0'
gem 'licensee', '~> 8.7'
gem 'sequel', '~> 4.6'
gem 'pg'
gem 'sqlite3', '~> 1.3'
